### ISSUE TITLE
Online/offline events support

### ISSUE THREAD

**Issue by Guria** [cerebral/cerebral-module-useragent#8]
https://developer.mozilla.org/en-US/docs/Online_and_offline_events
http://html5demos.com/offline

But:
http://stackoverflow.com/questions/3181080/how-to-detect-online-offline-event-cross-browser

**Comment by maxfrigge** [comment]
Mhh.. like the idea though. I could add support for online detection by "pinging" a url that needs to be set on module init.

What do you think @Guria?

**Comment by Guria** [comment]
@maxfrigge yeap, `offline.js` uses `favicon.ico` by default. Even 404 treated as online state

**Comment by maxfrigge** [comment]
@Guria I will try to just use offline.js.. seems more solid than DIY.

**Comment by maxfrigge** [comment]
@Guria I have added basic support for offline detection. 

It's currently in the develop branch and all it does is adding `useragent.network.offline` to the state and eventually update on change.. a bit tricky to test though.

Do you have a use case at hand where you could test it? 

What else might be useful? 
Should there be anything else helping the developer with online/offline situations?

**Comment by Guria** [comment]
Not ready to answer. It was just idea, offline checks is mot on priority on my projects

**Comment by maxfrigge** [comment]
Let's just assume it's sufficient for now :)

**Comment by maxfrigge** [comment]
Just realised that it's not merged yet.
